mochi-hpc/mochi-margo

include/margo.h
src/Makefile.subdir
src/margo-core.c
src/margo-init.c
src/margo-prio-pool.c
src/margo-prio-pool.h
tests/Makefile.subdir
tests/basic-ded-pool-prio.sh
tests/basic-prio.sh
tests/margo-test-server.c
tests/test-util-ded-pool.sh
tests/test-util.sh

This PR adds a new supported pool kind to the margo json, called "prio_wait".  It can be used in any place where "fifo_wait" would normally appear in the json.
This replaces the default pool implementation that margo uses with a custom one that will prioritize completing existing ULTs over starting new ones (in situations where both are eligible to execute).  Hypothetically this may help heavily oversubscribed servers make progress on in-flight RPCs faster, but we don't have measurements to support that hypothesis.

add priority pool option

---

src/margo-diag.c
src/margo-init.c

This PR makes it possible again to set the MARGO_ENABLE_DIAGNOSTICS and MARGO_ENABLE_PROFILING environment variables to enable those features at runtime without modifying the target application.
It also includes some minor memory leak fixes.
Fixes #75

honor environment variables to enable diagnostics and profiling at run time

---

src/margo-core.c
tests/Makefile.subdir
tests/error.sh
tests/margo-test-client-error.c

this PR is created for fix https://github.com/mochi-hpc/mochi-margo/issues/113 , and add test cases which this fix can resolved. 
this time added a case of communicating with a non-existent (=dummy address) server.
I tried to create a more realistic example with `na+sm` protocol, but it didn't work (please let me know if you can).
in `na+sm` protocol, if server is not exists, `HG_Forward` returns `HG_NODEV` and `margo_cb` is not called.
As I wrote in https://github.com/mochi-hpc/mochi-margo/issues/113 , timer is not removed if `margo_cb` is not called.
after that, timer is expired and call `HG_Cancel` with **already failed** request, it occurs segmentation fault.
To reproduce this, the timer needs to be expired after fails `HG_Forward` and before `margo_finalize`, so add `sleep 3s` in the …

Destroy timer on failed forwarding

---

src/margo-core.c

When failed forwarding, `eventual` is not used and freed,  so call `ABT_eventual_free(&eventual)`

free ABT_eventual when failed forwarding

---

tests/sleep.sh

This changes allows us to see a more detailed log when the `sleep.sh` test fails.

show log when failed sleep test

---

doc/instrumentation.md
src/margo-core.c
src/margo-init.c

This adds a json parameter (`output_dir`) and environment variable (`MARGO_OUTPUT_DIR`) that can be used to specify the default directory that profiling and diagnostics files will be emitted to if they are enabled at runtime.
If neither the json nor env dir are specified, then margo will still use the current working directory as before.
Fixes #57

configurable out dir for profiling and diag

---

include/margo.h
src/margo-core.c
src/margo-diag.c

- unify path parsing into one subroutine
- use margo logging rather than perror
- Inject output_dir path within API rather than expecting caller to do
so.  This can be overriden by passing an absolute path parameter.

refactor output file handline for diag/prof

---

README.md
doc/debugging.md
examples/margo-example-client.c
examples/margo-example-server.c
examples/my-rpc.c
examples/my-rpc.h
include/margo.h
maint/hooks/pre-commit
src/abtx_prof.h
src/margo-core.c
src/margo-diag.c
src/margo-globals.c
src/margo-globals.h
src/margo-init.c
tests/margo-test-client.c
tests/my-rpc.c
tests/my-rpc.h

Adds a `margo_state_dump()` function to dump point in time state from a margo instance.  PR includes example and documentation linked from README.
Current example (end of output is truncated; Argobots also displays extensive stack data in hex format):
```
{
"output_dir":"/tmp",
"version":"0.9.2",
"progress_timeout_ub_msec":100,
"enable_profiling":true,
"enable_diagnostics":true,
"handle_cache_size":32,
"profile_sparkline_timeslice_msec":1000,
"mercury":{
"version":"2.0.1",
"request_post_incr":256,
"request_post_init":256,
"auto_sm":false,
"no_bulk_eager":false,
"no_loopback":false,
"stats":false,
"na_no_block":false,
"na_no_retry":false,
"max_contexts":1,
"address":"na+sm://1005343/0",
"listening":true
},
"argobots":{
"abt_mem_max_num_stacks":8,
"abt_thread_stacksize":2097152, …
```

margo_state_dump() function

---

src/margo-core.c
tests/unit-tests/Makefile.subdir
tests/unit-tests/margo-init.c

Fixes #134 and #133 
This PR adds a unit test for finalizing and re-initializing margo in the same execution.
Also fixes two bugs:
- crash on re-initialization with profiling enabled
- old memory leak for abt thread-local keys used for rpc profiling

unit test and bug fix for init/finalize cycles

---

src/margo-core.c
src/margo-diag-internal.h
src/margo-diag.c
src/margo-init.c
tests/unit-tests/margo-diag.c

Fixes #137 
This PR also switches the margo_diag unit test from using environment variables to using runtime api calls to enable profiling.

make more robust to dynamic profiling

---

src/margo-init.c
tests/unit-tests/Makefile.subdir
tests/unit-tests/margo-abt-pool.c

Right now this PR just includes an initial test case (which doesn't pass).  See #142 
Need to do the following:
@roblatham00

fix bugs in pool kind specification for rpc pool

---

tests/unit-tests/Makefile.subdir
tests/unit-tests/margo-logging.c

These are very basic logging tests.  Mainly adding so that we have a basic framework to be able to test if warnings are emitted in various scenarios like #118 .

logging unit tests

---

src/margo-init.c
src/margo-logging.c
tests/unit-tests/margo-logging.c

The purpose is to make sure that we display any non-catastrophic warnings that occur during margo initialization.
The PR includes some test cases as well as some changes to error handling when querying abt features to avoid spurious warning messages.
This is a preliminary step towards addressing #118 .

enable warnings in global log

---

include/margo.h
src/margo-init.c
tests/unit-tests/Makefile.subdir
tests/unit-tests/margo-after-abt-init.c

- adds a utility function (`margo_set_environment()`) that can be used to set preferred Argobots parameters for Margo prior to external calls to ABT_init()
- modifies warning to rely on runtime query of Argobots API to confirm settings
- verbose warning message suggesting use of above function if settings are not in alignment
- extra test cases for external initialization of Argobots
- relies on changes that already landed in PR #147 to make sure that warnings are visible by default
Once this is available in a tagged release we should update other repos to use margo_set_environment() rather than manually setting parameters, so that they are future proof in case we change defaults or modify other settings in the future.
Fixes #118

improve handling of external Argobots initialization

---

src/margo-core.c

I don't know what Unify is doing but if I step through ROMIO code in the
debugger I can eventually cause the unifyfsd process to hit this
assertion.
Help the poor human decoding this error message!

Report unhandled errors in human readable format

---

tests/unit-tests/Makefile.subdir
tests/unit-tests/margo-scheduling.c

The test case is functional in that it displays the CPU time consumed by 5 seconds of Argobots mutex contention.  See https://github.com/pmodels/argobots/issues/361 for a discussion of the issue.
Before this can be merged we need to:

test case for mutex busy spin behavior

---

src/margo-abt-macros.h
src/margo-core.c
src/margo-instance.h

This PR enables using ABT_eventual_memory instead of ABT_eventual in margo requests. This allows keeping the eventual on the stack.
I tested with argobots@main (which has ABT_eventual_memory) and with argobots@1.1 (which doesn't) and `make check` passes fine.
@carns I let you take a look and merge if you're satisfied.
Note that this PR also adds a similar mechanism for mutex, but I didn't find any mutex allocated in a critical path so I didn't change anything. One mutex that could be changed is the global mutex (in margo-globals.c), but I think this should be made an ABT_mutex_memory, not something selected based on whether ABT_mutex_memory is available. I think using ABT_mutex_memory would require making margo depend on argobots@1.1 (or an earlier version, but at least I know …

Use ABT_eventual_memory in margo requests

---

tests/unit-tests/Makefile.subdir
tests/unit-tests/margo-eventual.c

Test case for margo_eventual_t.  This test case will fail if static eventuals are not safe to use on an emphemeral function call stack.

unit test for eventuals

---

tests/unit-tests/margo-comm-error.c

- rather than checking for a specific error code (which no longer holds
in mercury 2.1.0rc3), instead just make sure that it is a non-success,
non-timeout error

relax error code assertion in unit test

---

include/margo.h
src/margo-core.c

Fix possible race due to checking if margo is finalized then incrementing pending requests.

fixed possible race in DEFINE_RPC_HANDLER macro

---

include/margo.h
src/margo-core.c
tests/unit-tests/Makefile.subdir
tests/unit-tests/margo-comm-finalize.c

- if incoming rpcs are in flight (either about to start a handler, or
already in a handler) when an rpc is deregistered, then they will fail
to retrieve the mid pointer associated with the handle because the
stored pointer has been reset.  Handle this case rather than assuming
it will always work.
- includes new unit test that deliberately deregisters a handler in the
middle of a flurry of incoming RPCs

fix race between deregister and incoming rpcs

---

configure.ac
m4/ax_pthread.m4
maint/margo.pc.in

- use gnu ax_pthread m4 macro
- report required flags in .pc file
Fixes #175

explicit pthread dependency

---

src/margo-init.c

- na_max_unexpected_size and na_max_expected_size to control raw message size limits at na layer (json input)
- input_eager_size and output_eager_size to report effective api-level eager limits on input and output struct sizes (json output)
This PR needs review because I'm not 100% sure it is working as expected.  My expectation is that setting the na_max sizes should influence the eager sizes reported to the user (the latter is derived from the former after accounting for message header overheads).
This is the default values that I see on my laptop with na+sm, using the `margo-test-init-ext` test program to display runtime json:
```
> tests/margo-test-init-ext &| grep _size |grep -v handle
"input_eager_size":4080,
"output_eager_size":4080
```
I then specify the na msg sizes as follows: …

json fields to set and query mercury msg sizes

---

src/margo-core.c
src/margo-diag.c
src/margo-init.c
src/margo-instance.h

- only call it once (at init time) and save result in mid
- check for errors and log if addr can't be resolved
Rather than alter the macro, this PR just reduces the usage to a single caller at init time and does error checking there.
Fixes #182

clean up use of GET_SELF_ADDR_STR

---

include/margo.h
src/margo-core.c
src/margo-instance.h
src/margo-serialization.h
tests/unit-tests/margo-comm-error.c

This PR changes the way serialization is done in Margo: instead of relying on the user-provided proc callbacks, these proc callbacks are attached to the RPC data. The generic `margo_forward_proc` and `margo_respond_proc` functions, defined in margo-serialization.h, are used instead when registering RPCs. These functions are being passed a structure that includes (1) the user-provided proc callback, (2) the user-provided data, and (3) a header to append to the buffer.
In the case of the response, the header contains an `hg_return_t` error code that, if set to something else than `HG_SUCCESS`, will abort the serialization and forward just that error code back to the client. The error code will then be returned by `margo_get_output` when the client tries to deserialize the output.
This …

Reworked serialization mechanism to add a custom header embedding error codes

---

include/margo.h
src/margo-core.c
tests/unit-tests/Makefile.subdir
tests/unit-tests/margo-bulk.c

Do not merge until https://github.com/mercury-hpc/mercury/pull/559 lands and we can validate what mercury version number to key off of in the #if guards.
Fixes #184

optional margo_bulk_create_attr() wrapper

---

configure.ac
src/margo-core.c
src/margo-init.c

This adds a `"lazy_stack_alloc":true` boolean to the argobots json object in margo to indicate if lazy stack allocation is enabled in Argobots, based on a runtime query.
The boolean is not displayed at all if Argobots does not expose this query parameter.

report in json if abt lazy stack allocation is enabled

---

include/margo.h
src/margo-init.c

New json parameter to enable Mercury support for RDMA to device memory.
Can be enabled with a Margo json config block that looks like this:
```
{
"mercury":{
"na_request_mem_device":true
}
}
```
Fixes #194

add support for na.request_mem_device

---

include/margo.h
src/margo-core.c

This PR fixes https://github.com/mochi-hpc/mochi-margo/issues/202.
The solution is actually simple and does not require us to wait for a fix in Mercury: since we already had a `_handler_for_NULL = NULL` defined in our macro to handle the case `MARGO_REGISTER(... NULL)`, I just needed to give it an actual definition in which I can return an `HG_NOENTRY` via the response.
This makes the margo-forward unit test pass.

fixed problem where sending invalid RPC would return HG_SUCCESS

---

tests/unit-tests/margo-abt-pool.c
tests/unit-tests/margo-addr.c
tests/unit-tests/margo-after-abt-init.c
tests/unit-tests/margo-bulk.c
tests/unit-tests/margo-comm-error.c
tests/unit-tests/margo-comm-finalize.c
tests/unit-tests/margo-forward.c
tests/unit-tests/munit/munit-goto.h
tests/unit-tests/munit/munit.c

This PR provides `munit_assert_*_goto` macro that take an extra `label` argument and do a `goto label` instead of a `longjump`. This allows to stay in the test and manually return `MUNIT_FAIL` after that label. Some of the unit tests have been updated as examples.

Fixing munit tests hanging after a failure

---

include/margo.h
src/margo-core.c

This PR is a solution to the scenario where a user registers a provider with id 0 and another one with id 1, then creates a client, then destroys the provider with id 0. In this situation right now the client will no longer be able to communicate with the provider 1 because the destruction of provider 0 will have deregistered its RPCs.
This PR "solves" this by making the default provider id (used to register clients) 0xFFFF (the max for a uint16_t) instead of 0, modifying the mux/demux functions accordingly. Technically it doesn't solve the problem since someone could still register a provider with id 0xFFFF, then a client, then destroy the provider, and that would leave the client unable to use its RPCs as well. But it's less likely that a user will register a provider with id 0xFFFF, …

Changes the default provider id (used by clients) from 0 to 0xFFFF

---

examples/composition/data-xfer-service.c
examples/composition/delegator-service.c
examples/multiplex/svc1-server.c
examples/multiplex/svc2-server.c
examples/my-rpc.c
include/margo.h
src/margo-core.c
src/margo-diag.c
src/margo-instance.h
tests/my-rpc.c
tests/unit-tests/margo-comm-finalize.c

There are many placed in margo where `HG_Registered_data` must be used to retrieve information about an RPC. This includes at least when creating an `hg_handle_t`, when forwarding it, when responding, when getting and freeing input and output, and whenever getting the margo instance from a handle. `HG_Registered_data` takes the RPC id as argument, hence incurring a hash lookup in Mercury.
This PR replaces the use of `HG_Registered_data` with the use of `HG_Get_data`, which works on data associated with a handle rather than data associated with the RPC. The RPC data is copied into the handle's data when the handle is created (whether in `margo_create` or in the handler macro on servers), then all the calls to `HG_Registered_data` can be replaced with calls to `HG_Get_data`, removing hash …

Replace the use of HG_Registered_data with HG_Get_data

---

configure.ac
src/margo-info.c

This adds a new section (on supported platforms, i.e. Linux) that displays runtime libraries as follows:
```
####################################################################
####################################################################
```
If the GNU-specific routine used to query this is not detected at configure time, then this section is omitted.  By default it only displays libraries that string match against expected communication library names, but as indicated above it will show all libraries if the -l option is given on the command line.

display runtime libraries in margo-info output

---

configure.ac

This modifies the autoconf script to explicitly pass along rpath information for dependent libraries to libtool via the -R option.  It resolves runtime "library not found" errors when linked against dependencies that were installed via spack origin/develop as of 2022-08-16.
This works, but I'm not sure if it's a good solution.  It may not cover all cases, and a similar strategy would need to be repeated in any external autotools software packages that rely on our libraries (for example, imagine an app that in turns relies on a libmargo library installed by spack and will need to set an rpath to refer to it).
This is only needed now due to a policy change in spack that prevents it from automatically exporting LD_LIBRARY_PATH for loaded packages.
@mdorier

library path workaround

---

src/margo-info.c

Fixes #217 
- replace invalid ucx+verbs address string with ucx+rc, ucx+dc, and ucx+ud
- add more guidance in output on meaning of ucx address strings
- allow query of address strings that are unknown to the margo-info utility

improve margo-info address handling

---

include/margo.h
src/margo-core.c
tests/unit-tests/margo-init.c

This PR adds the `margo_finalize_and_wait` function.
Contrary to `margo_finalize`, which only "requests" the margo instance to be finalized (something that may actually be done by, e.g., the last pending RPC), `margo_finalize_and_wait` actually blocks until the margo instance is cleaned up and has finalized.
Contrary to `margo_wait_for_finalize`, `margo_finalize_and_wait` requests that the instance finalizes.
The unit test tests the scenario of just initializing and finalizing a margo instance, in which case `margo_finalize_and_wait` will be the function that actually calls finalize. It also tests a scenario in which an RPC is received that takes 1 second to complete. Because the RPC is pending, `margo_finalize_and_wait` will block until the RPC completes. This is checked by looking at …

added margo_finalize_and_wait function and unit test for it

---

include/margo.h
src/margo-core.c
src/margo-instance.h
tests/unit-tests/margo-forward.c
tests/unit-tests/munit/munit-goto.h

This simple PR adds the two functions listed in the title, to retrieve the name provided when the RPC was registered, respectively from an `hg_id_t` and from an `hg_handle_t`.
There is a unit test that goes with it (in margo-forward.c).
I used these functions in the macros in margo.h to provide the correct RPC name to logging functions. Previously, these macros were using `#__name`, which is the name of the C function, not the name under which the RPC is registered. This was problematic for any thallium- or pymargo-based library since these libraries register a single, generic C callback that then dispatch to the actual RPC function (so the trace would show things like "Calling RPC generic_thallium_rpc" instead of "Calling the_name_the_user_registered_with").
More generally, these …

margo_rpc_get_name and margo_handle_get_name

---

configure.ac

Reverts mochi-hpc/mochi-margo#196
This logic is fragile as written and will sometimes produce invalid libtool command line arguments if dependent libraries are in the system library path.
Revert this and just rely on spack settings to avoid spack-specific runtime library path issues.

Revert "library path workaround"

---

configure.ac
include/margo-config.h
src/margo-abt-config.c
src/margo-abt-config.h
src/margo-config.c
src/margo-core.c
tests/unit-tests/Makefile.subdir
tests/unit-tests/margo-elasticity.c

This PR brings the following functions in `margo-config.h`:
- `margo_add_pool_from_json`: adds (create) a pool using a JSON description (same as pool definitions in margo config);
- `margo_add_pool_external`: makes margo aware of an externally-initialized pool (also provides the option to give ownership of this pool to the margo instance);
- `margo_add_xstream_from_json`: adds (create) an xstream using a JSON description (same as xstream definitions in margo config);
- `margo_add_xstream_external`: makes margo aware of an externally-initialized xstream (also provides the option to give ownership of this xstream to the margo instance);
- `margo_remove_pool_by_index/name/handle`: removes a pool specified by its index or name or handle (free the pool if margo has ownership of it);
- …

Functions to add and remove pools and xstreams

---

tests/unit-tests/margo-forward.c

change was prompted by interference from docker virtual network on some systems, but the built-in mercury sm protocol is more commonly available anyway and is already assumed present by other unit tests

use na+sm as transport for unit tests

---

examples/margo-example-server.c
src/margo-abt-profiling.c
src/margo-config.c
src/margo-init.c
tests/unit-tests/test-configs.json

Fixes #245 
- disable abt profiling by default
- start profiler if requested by config
- do not attempt to print profile statistics if profiler not started

clean up argobots profiling

---

include/margo.h
src/margo-core.c
src/margo-instance.h
tests/unit-tests/margo-forward.c

This PR introduces 4 new functions:
- margo_cforward
- margo_provider_cforward
- margo_cforward_timed
- margo_provider_cforward_timed
They work like the `margo_iforward` variants in that they immediately return to the caller, but instead of taking a pointer to a `margo_request` to set, they take a callback and argument to be called upon completion of the RPC (or timeout).
There is a unit test testing these functions.
Technically I could also add margo_crespond and margo_bulk_ctransfer families of functions, but cforward is the most useful. It will allow for instance to forward an RPC to N destinations and do something upon completion of each RPC without having to actively loop through an array of margo_requests.
Note: intuitively the margo_iforward functions should be rewritten to make …

cforward functions (forward with callback)

---

src/margo-abt-config.c
tests/unit-tests/test-configs.json

- the "default" scheduler refers to the Argobots default, which causes idle execution streams to spin looking for new work units
- the "basic_wait" scheduler is the one that pairs with the "fifo_wait" pool type that we are using by default and will suspend until work is available
Fixes #248.
Once this is validated and merged then I'll update the scheduling unit test to fail if CPU usage is too high.

use "basic_wait" as the default scheduler

---

include/margo.h
src/margo-core.c
src/margo-init.c
src/margo-instance.h
tests/unit-tests/margo-init.c

This PR is a response to issue https://github.com/mochi-hpc/mochi-margo/issues/260
@carns Could you review it?
Note: it does not change the semantics of any program written so far, nor is the use of the new functions required. They are just convenient in particular in C++ codes that want to rely on reference counting for memory management.
This PR comes with two extra suggestions:
- Should we add a check at the beginning of all the margo functions that the instance has not been finalized, or is it the responsibility of the user to ensure that they don't call functions on a finalized instance? (the latter doesn't differ from what is done right now)
- Should we move ABT_finalize to when the instance is freed, as opposed to finalized, so it gives a chance to codes that rely on this …

Add refcount to margo instance

---

Makefile.am
configure.ac
include/margo-hg-shim.h
maint/margo-hg-shim.pc.in
maint/margo.pc.in
src/Makefile.subdir
src/margo-hg-shim.c
tests/unit-tests/margo-forward.c

This PR adds a `margo-hg-shim` library, with a `margo-hg-shim.h` header and a `margo-hg-shim.pc` file to find them. The purpose of this library is to provide a set of `HG_*` functions meant for a Mercury-based code to interact with a Margo-based code.
This solves the same problem as https://github.com/mochi-hpc/mochi-margo/pull/256 but in a cleaner way from Margo's perspective (making Mercury aware of the Margo headers and way of generating the RPC id instead of disabling the headers on Margo's side).
@marcvef can you give it a try? the tests/unit-tests/margo-forward.c file has an example of using these functions.

margo-hg-shim library

---

src/margo-id.h
tests/unit-tests/margo-monitoring.c

DO NO MERGE UNTIL RESOLVED
This is a merge request to force github actions to run, but right now it's a bug. I have changed the `gen_id` function in `margo-id.h` from this:
```
static inline hg_id_t gen_id(const char* func_name, uint16_t provider_id)
{
hg_id_t  id;
unsigned hashval;
HASH_JEN(func_name, strlen(func_name), hashval);
id = hashval << (__MARGO_PROVIDER_ID_SIZE * 8);
id |= provider_id;
return id;
}
```
to this:
```
static inline hg_id_t gen_id(const char* func_name, uint16_t provider_id)
{
hg_id_t  id;
unsigned hashval;
HASH_JEN(func_name, strlen(func_name), hashval);
id = hashval;
id = id << 32;
id |= (hg_id_t)provider_id;
return id;
}
```
In the original version `hashval << (__MARGO_PROVIDER_ID_SIZE * 8)` is executed before the result is assigned to `id`. Since `hashval` is …

[BUG] Using the full 64 bits of hg_id_t for the hash

---

spack.yaml
src/Makefile.subdir
src/margo-abt-config.c
src/margo-abt-config.h
src/margo-efirst-pool.c
src/margo-efirst-pool.h
tests/unit-tests/margo-abt-pool.c
tests/unit-tests/margo-forward.c

The `erliest_first` pool is a pool that prioritizes the ULTs based on the order in which they have been created. It does so using a min-heap-based priority queue + a FIFO queue.
The pool maintains a counter of ULTs created in it since its creation. When a new ULT is created and pushed into the pool, its priority is set to the pool's current counter and the counter is increased. The ULT is placed in the min-heap priority queue. Each ULT also keeps track of how many time it has been popped from the pool. When the ULT is pushed back in the pool, if this number is lower than 32, it goes back in the priority queue. If it's greater or equal to 32, it goes into the FIFO queue. The FIFO queue represents "old" (potentially long-running) ULTs, for which it no longer makes sense to assign a …

Add implementation of "earliest_first" pool

---

tests/unit-tests/margo-eventual.c

Looking into fixing https://github.com/mochi-hpc/mochi-margo/issues/266.
There was 2 problems with the margo_eventual test:
- The eventual is created, waited, and freed by the "waiter_fn", and set of by "setter_fn". This assumes that the setter function does not start before the waiter, otherwise it gets a garbage data instead of an eventual because the eventual hasn't been created (normally this shouldn't happen because of `margo_thread_sleep` though, but better write a correct program to begin with). In all of margo, the eventual is always created before anything is going to attempt to access it.
- The eventual was freed twice. Once in the waiter_fn, and another time at the end of the test function. I don't think we ever ran into a problem with that because with a recent enough version …

fixing margo-eventual unit test

---

include/margo.h
src/Makefile.subdir
src/margo-core.c
src/margo-identity.c
src/margo-init.c
src/margo-instance.h
tests/unit-tests/Makefile.subdir
tests/unit-tests/margo-identity.c
tests/unit-tests/margo-monitoring.c

Adds an API to associate a provider name with a provider ID, making querying such a name possible remotely.
Note: because "name" is used often to refer to RPC name (e.g. margo_register_name), I decided to use the term "identity" instead for provider. In practice, we will in fact use it to register the type of provider ("yokan", "warabi", etc.) rather than a unique name, so an "identity" is more suitable.

Dev provider names

---

.github/workflows/codecov.yml
include/margo-timer.h
src/margo-core.c
src/margo-init.c
src/margo-instance.h
src/margo-timer-private.h
src/margo-timer.c
tests/unit-tests/margo-timer.c

This PR improves the timers API in a few ways:
- It adds `margo_timer_create_with_pool` to specify the pool in which the timer's callback should be submitted as a ULT. If ABT_POOL_NULL is passed, the callback will be executed in the context of the progress loop. I added a warning in the function's documentation that this should be avoided and has limitations (such as not being allowed to call any margo functions in the callback since they could deadlock).
- It changes the semantics of `margo_timer_cancel()`. Previously, this function would only remove the timer from the list of future timers, but would not cancel a ULT submitted by the timer. Now it does, and it also waits for completion of any ULT submitted by the timer. This guarantees that after `margo_timer_cancel()` returns, the …

Improved timers

---

include/margo-monitoring.h
src/margo-default-monitoring.c
src/margo-monitoring.c
tests/unit-tests/margo-monitoring.c

This PR adds a `margo_monitor_dump` function that takes a function pointer and calls it with a serialized representation of the monitor's state. If reset is set to true, this function will also reset to monitor's state.

Implemented margo_monitor_dump

---

include/margo-monitoring.h
src/margo-config.c
src/margo-default-monitoring.c

This PR fixes a bug that happens if we add a pool when monitoring (in particular time series) is enabled. The current problem is that because there is no time series structure allocated for the new pool, the default monitoring system will access an array out of range, causing a segfault.
To solve this problem, this PR makes the following changes:
- It adds monitoring callbacks invoked when pools and xstreams are added and removed, to give a chance for the monitoring framework (whether default or custom) to react to such a change (e.g. by allocating/deallocating the proper data structures);
- It implements these callbacks for the default monitoring framework, allocating and moving the the time series as appropriate when a pool is added/removed.

Fix monitoring when adding pools

---

src/margo-core.c
tests/unit-tests/margo-init.c

This PR fixes an issue that appears when we have 2 pools, with the progress loop running on the second one. It we are in a situation where the progress loop is the only ULT in its pool, it's never going to yield and never going to give a chance for the scheduler to check the first pool again, even if that first pool could have ULTs available to run.
The fix adds `ABT_thread_yield` right after `HG_Progress` so that we give a chance for the scheduler to take over.
Note that while this fixes the starvation problem, it highlights a potential other issue (performance related, this time): if the progress loop is alone in its pool, `HG_Progress` will be called with a timeout of 100ms, even though ideally we would want to call it with a timeout of 0 so that we can immediately yield and check …

Fix yielding in progress loop

---

src/margo-init.c
tests/unit-tests/Makefile.subdir
tests/unit-tests/margo-sanity-warnings.c

This PR adds warnings if the configuration is such that some pools could be starved.

Print warnings if configurations could lead to deadlocks or starvation scenarios

---

src/margo-logging.c

This PR addresses https://github.com/mochi-hpc/mochi-margo/issues/275. It adds the possibility to set `MARGO_LOG_LEVEL` to one of the levels ("trace", "debug", "info", "warning", "error", "critical"). This variable applies to the requested log level for the global logger. The PR also makes any instance-specific logger inherit the level from the global logger at creation time, instead of being set to "warning".

Add the possibility to specify logging level via an environment variable

---

include/margo.h

- bug fix: the rpc_name is an internal pointer that may not necessarily be valid after completion of an RPC handler if the process unregisters an RPC fast enough
Alternatively we could strdup the rpc name to make sure the RPC wrapper has a copy that stays in scope, but I don't think the information is worth the memory allocation.  The handle pointer value is sufficient to map back to the preceding trace message if needed.

don't print rpc_name pointer after handler exec

---

src/margo-core.c

improves ops/s by 2-3% in sequntial benchmarks

remove superfluous ABT_thread_yield() call

---

src/margo-config.c
src/margo-core.c
src/margo-init.c
src/margo-instance.h
tests/unit-tests/test-configs.json

This PR makes it so that once Margo starts to busy spin (because of in flight RPCs or active ULTs in the progress pool) , it will continue to do so for a brief, configurable period of time.
The intent is to make Margo slightly less aggressive about entering an idle mode.  It should improve performance particularly for sequential workloads that have small rtt gaps between operations.
Need to performance test before merging but I want to go ahead and open a PR so that it can to through github CI checks.

add spindown parameter

---

configure.ac
src/margo-config.c
src/margo-core.c
src/margo-hg-config.c
src/margo-hg-config.h
src/margo-init.c
src/margo-instance.h

Adds optional support for the mochi-plumber library and json parameters to configure it.

add mochi-plumber support for automatic network card selection
